import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def plot_differences(zig_csv, py_csv, title, columns_to_compare):
    try:
        df_zig = pd.read_csv(zig_csv)
        df_py = pd.read_csv(py_csv)
    except FileNotFoundError as e:
        print(f"Missing file for comparison: {e}")
        return

    # Ensure timestamps align
    if not np.allclose(df_zig['timestamp_s'], df_py['timestamp_s']):
        print(f"Warning: Timestamps in {title} do not perfectly align!")

    # Calculate absolute differences
    diff_df = pd.DataFrame({'timestamp_s': df_zig['timestamp_s']})
    for col in columns_to_compare:
        diff_df[col] = np.abs(df_zig[col] - df_py[col])

    # Plotting
    plt.figure(figsize=(12, 6))
    for col in columns_to_compare:
        plt.plot(diff_df['timestamp_s'], diff_df[col], label=f'{col} error', alpha=0.8)

    plt.title(f"Absolute Difference (PyTorch vs Zig/C Int8): {title}")
    plt.xlabel("Timestamp (s)")
    plt.ylabel("Absolute Logit Difference")
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.savefig(f"{title.lower().replace(' ', '_')}_diff.png")
    plt.show()

if __name__ == "__main__":
    # 1. Compare Sleep Phase Models
    plot_differences(
        zig_csv="outputs/sleep_preds.csv",
        py_csv="outputs/py_sleep_preds.csv",  # Generated by your PyTorch script
        title="Sleep Stage MLP",
        columns_to_compare=['wake', 'light_sleep', 'deep_sleep', 'rem']
    )
    
    # 2. Compare Arousal Models
    plot_differences(
        zig_csv="outputs/arousal_preds.csv",
        py_csv="outputs/py_arousal_preds.csv", # Generated by your PyTorch script
        title="Arousal Detector",
        columns_to_compare=['arousal_logit']
    )